---
- name: Install and configure httpd
  hosts: webserver
  become: yes
  tasks:
    - name: Install httpd & firewalld
      yum:
        name: 
          - httpd
          - firewalld
        state: latest
    - name: Service Start
      service:
        name: httpd
        state: started
        enabled: true
    - name: Enable and start Firewalld
      service:
        name: firewalld
        enabled: true
        state: started
    - name: Open firewall ports
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
    - name: Copy html Content
      copy:
        content: "welcome to our new session past 1 year ago "
        dest: /var/www/html/index.html
- name: Test and verify webserver
  hosts: localhost
  become: no
  tasks:
    - name: Connect to the webserver
      uri:
        url: http://node1
        status_code: 200
